sudo: false

addons:
  apt:
    sources:
      - cassou-emacs
    packages:
      - emacs24
      - emacs-snapshot

language: emacs-lisp

env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs-snapshot

before_install:
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="$HOME/.cask/bin:$PATH"
  - export ECUKES_EMACS="$EMACS"
  - export UNDERCOVER_SEND_REPORT=1
  - cask

script:
  - cask exec ecukes --no-win -r magnars
